# Generated by Django 2.0.2 on 2018-04-02 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180211_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
