# Generated by Django 2.0.2 on 2018-04-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180402_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='title',
            field=models.CharField(blank=True, default='attack-pattern--', max_length=100),
        ),
    ]
